services:
    _defaults:
        autowire: true
        autoconfigure: true

    MartenaSoft\AdminBundle\:
        resource: '../../../src/'
        exclude:
            - '../../../src/DependencyInjection/'
            - '../../../src/Entity/'
